# =================================================================================================

from snakemake.utils import min_version

# Make Sure Minimun Snakemake version
min_version("6.10")

# Load config file
configfile: "../config/config.yaml"

# Description of the workflow can be found in the final report
report: "report/workflow.rst"

# =================================================================================================

include: "rules/common.smk"     
include: "rules/qc.smk"
include: "rules/trimming.smk"
include: "rules/build_kmers_gwas.smk"
include: "rules/count_kmers.smk"
include: "rules/combine_and_filter_kmers.smk"
include: "rules/generate_kmers_table.smk"
include: "rules/generate_kinship_matrix.smk"
include: "rules/kmers_gwas.smk"

# =================================================================================================

rule all:
    input: 
        get_target_output,