# =================================================================================================

from snakemake.utils import min_version

# Make Sure Minimun Snakemake version
min_version("6.10")

# =========================================================================================================
#     Setup Config and Report
# =========================================================================================================

# Load config file
configfile: "../.test/config/maize_config.yaml"

# validate(config, schema="../schemas/config.schema.yaml")

# Description of the workflow can be found in the final report
report: "report/workflow.rst"

# =========================================================================================================
#     Load Rules
# =========================================================================================================

include: "rules/common.smk"     
include: "rules/qc.smk"
include: "rules/trimming.smk"
include: "rules/build_kmers_gwas.smk"
include: "rules/count_kmers.smk"
include: "rules/combine_and_filter_kmers.smk"
include: "rules/generate_kmers_table.smk"
include: "rules/generate_kinship_matrix.smk"
include: "rules/kmers_gwas.smk"
include: "rules/summarize_results.smk"
include: "rules/fetch_kmers.smk"
include: "rules/filter_kmers.smk"
include: "rules/ref.smk"
include: "rules/align_kmers.smk"
include: "rules/fetch_reads.smk"
include: "rules/align_reads.smk"

# =========================================================================================================
#     Target Outputs
# =========================================================================================================

rule all:
    input:
        get_target_output,
